name: Build and push binaries
on: [push]

permissions:
  contents: write

jobs:
  Release-Binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Fetch all tags
        run: git fetch --force --tags
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.7"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
